development:
  adapter: postgres
  database: hyperarchy_development
  username: hyperarchy

test:
  adapter: postgres
  database: hyperarchy_test
  username: hyperarchy

staging:
  adapter: postgres
  database: hyperarchy_staging
  username: hyperarchy

production:
  adapter: postgres
  database: hyperarchy_production
  username: hyperarchy
