development:
  adapter: postgresql
  encoding: unicode
  database: decider_development
  pool: 5
  username: nathansobo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: decider_test
  pool: 5
  username: nathansobo
  password:
