development:
  adapter: postgres
  database: hyperarchy_development
  username: hyperarchy

test:
  adapter: postgres
  database: hyperarchy_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: hyperarchy

demo:
  adapter: postgres
  database: hyperarchy_demo
  username: hyperarchy

production:
  adapter: postgres
  database: hyperarchy_production
  username: hyperarchy
