development:
  adapter: postgres
  database: hyperarchy_development
  username: hyperarchy

test:
  adapter: postgres
  database: hyperarchy_test
  username: hyperarchy

jasmine:
  adapter: postgres
  database: hyperarchy_jasmine
  username: hyperarchy

demo:
  adapter: postgres
  database: hyperarchy_demo
  username: hyperarchy

production:
  adapter: postgres
  database: hyperarchy_production
  username: hyperarchy
