every_5_mins_notifications:
  cron: "*/1 * * * *"
  class: Jobs::SendNotifications
  args:
    - period: "every5"
  description: "Sends every-5-minute email notifications"

hourly_notifications:
  cron: "0 0 * * * *"
  class: Jobs::SendNotifications
  args: "hourly"
  description: "Sends hourly email notifications"
